#define TK_ILLEGAL                         1
#define TK_SPACE                           2
#define TK_COMMENT                         3
#define TK_FUNCTION                        4
#define TK_INSERT                          5
#define TK_INTO                            6
#define TK_VALUES                          7
#define TK_DELETE                          8
#define TK_TOP                             9
#define TK_IN                             10
#define TK_TINYINT                        11
#define TK_SMALLINT                       12
#define TK_INT                            13
#define TK_FLOAT                          14
#define TK_ISNULL                         15
#define TK_ISNOTNULL                      16
#define TK_TIMEVAL                        17
#define TK_ADD                            18
#define TK_USER                           19
#define TK_IDENTIFIED                     20
#define TK_BY                             21
#define TK_STRING                         22
#define TK_SEMI                           23
#define TK_DROP                           24
#define TK_SET                            25
#define TK_PASSWORD                       26
#define TK_FOR                            27
#define TK_EQ                             28
#define TK_LP                             29
#define TK_RP                             30
#define TK_ROLE                           31
#define TK_ID                             32
#define TK_TABLE                          33
#define TK_ATTACH                         34
#define TK_DETACH                         35
#define TK_DATAFILE                       36
#define TK_COMMA                          37
#define TK_FROM                           38
#define TK_CREATE                         39
#define TK_ALTER                          40
#define TK_BOOL_TYPE                      41
#define TK_BIGINT_TYPE                    42
#define TK_DOUBLE_TYPE                    43
#define TK_STRING_TYPE                    44
#define TK_BLOB_TYPE                      45
#define TK_DATETIME_TYPE                  46
#define TK_REAL2_TYPE                     47
#define TK_REAL3_TYPE                     48
#define TK_REAL4_TYPE                     49
#define TK_REAL6_TYPE                     50
#define TK_SELECT                         51
#define TK_STAR                           52
#define TK_AS                             53
#define TK_WHERE                          54
#define TK_GROUP                          55
#define TK_ORDER                          56
#define TK_ASC                            57
#define TK_DESC                           58
#define TK_LIMIT                          59
#define TK_INTEGER                        60
#define TK_AND                            61
#define TK_NE                             62
#define TK_GT                             63
#define TK_GE                             64
#define TK_LT                             65
#define TK_LE                             66
#define TK_LIKE                           67
#define TK_IS                             68
#define TK_NOT                            69
#define TK_NULL                           70
#define TK_TRUE                           71
#define TK_FALSE                          72
#define TK_DOUBLE                         73
#define TK_PLUS                           74
#define TK_MINUS                          75
#define TK_UINTEGER                       76
#define TK_UDOUBLE                        77
#define TK_BLOB                           78
