#define TK_ILLEGAL                         1
#define TK_SPACE                           2
#define TK_COMMENT                         3
#define TK_FUNCTION                        4
#define TK_INSERT                          5
#define TK_INTO                            6
#define TK_VALUES                          7
#define TK_DELETE                          8
#define TK_TOP                             9
#define TK_TRUE                           10
#define TK_FALSE                          11
#define TK_IN                             12
#define TK_TINYINT                        13
#define TK_SMALLINT                       14
#define TK_INT                            15
#define TK_ISTRUE                         16
#define TK_ISFALSE                        17
#define TK_FLOAT                          18
#define TK_ISNULL                         19
#define TK_ISNOTNULL                      20
#define TK_ADD                            21
#define TK_USER                           22
#define TK_IDENTIFIED                     23
#define TK_BY                             24
#define TK_STRING                         25
#define TK_SEMI                           26
#define TK_DROP                           27
#define TK_SET                            28
#define TK_PASSWORD                       29
#define TK_FOR                            30
#define TK_EQ                             31
#define TK_LP                             32
#define TK_RP                             33
#define TK_ROLE                           34
#define TK_ID                             35
#define TK_TABLE                          36
#define TK_ATTACH                         37
#define TK_DETACH                         38
#define TK_DATAFILE                       39
#define TK_COMMA                          40
#define TK_FROM                           41
#define TK_CREATE                         42
#define TK_ALTER                          43
#define TK_BOOL_TYPE                      44
#define TK_BIGINT_TYPE                    45
#define TK_DOUBLE_TYPE                    46
#define TK_STRING_TYPE                    47
#define TK_BLOB_TYPE                      48
#define TK_DATETIME_TYPE                  49
#define TK_REAL2_TYPE                     50
#define TK_REAL3_TYPE                     51
#define TK_REAL4_TYPE                     52
#define TK_REAL6_TYPE                     53
#define TK_SELECT                         54
#define TK_STAR                           55
#define TK_AVG_FUNC                       56
#define TK_COUNT_FUNC                     57
#define TK_LAST_FUNC                      58
#define TK_MAX_FUNC                       59
#define TK_MIN_FUNC                       60
#define TK_SUM_FUNC                       61
#define TK_FIRST_FUNC                     62
#define TK_AS                             63
#define TK_WHERE                          64
#define TK_GROUP                          65
#define TK_INTEGER                        66
#define TK_ORDER                          67
#define TK_ASC                            68
#define TK_DESC                           69
#define TK_LIMIT                          70
#define TK_AND                            71
#define TK_NE                             72
#define TK_GT                             73
#define TK_GE                             74
#define TK_LT                             75
#define TK_LE                             76
#define TK_LIKE                           77
#define TK_IS                             78
#define TK_NOT                            79
#define TK_NULL                           80
#define TK_DOUBLE                         81
#define TK_PLUS                           82
#define TK_MINUS                          83
#define TK_UINTEGER                       84
#define TK_UDOUBLE                        85
#define TK_BLOB                           86
